### PR TITLE
Remove tumbleweed ci workflow 🔥 

### PR DESCRIPTION
**Pull request by jonathangreen**
~~The tumbleweed CI workflow was failing because we needed to specify `--non-interactive` to `zypper` and remove the now unsupported python 3.8 version.~~

Based on the conversation on this PR, it has been updated to just completely drop the tumbleweed CI tests.

### CODE REVIEW

**Comment by agronholm** [comment]
Any idea why this workflow even exists?

**Comment by jonathangreen** [comment]
Nope! I'd be happy to just see it be deleted 🔥

**Comment by agronholm** [comment]
On another note, do you know any way to reach the developers, like Discord, Gitter, IRC...? There are several aspects of the project I'd like to discuss with them.

**Comment by jimjag** [comment]
I agree that tumbleweed should be removed. Maybe we should just do that and close this PR

**Comment by agronholm** [comment]
Would you be open to a more comprehensive, sweeping clean-up of the test suite? Also, how do you do releases? I have my own very nice workflow for that which you could adopt if you want to.

**Comment by jimjag** [comment]
@agronholm Yes, as long as we are cleaning up workflows, would love to see what you have in mind.

**Comment by agronholm** [comment]
I'll tinker with my own fork for a while. I'll open a new PR when I have something worthy of merging.

**Comment by agronholm** [comment]
Is there a chat forum where I could talk to you guys in real time?

**Comment by agronholm** [comment]
Tinkering with the build process turned out to be much harder than I expected. I noticed that the process involves creating both static and dynamic builds for all platforms. What's the rationale for this, and is this something you still want to keep doing?

**Comment by agronholm** [comment]
@jimjag you forgot to remove the badge in the README.

**Pull request closed without merging**
