### PR TITLE
Add compatibility with  xmlsec 1.3.3

### PR DESCRIPTION
**Pull request by ayakael**
Fixes https://github.com/xmlsec/python-xmlsec/issues/279

### CODE REVIEW

**Comment by deronnax** [comment]
@ayakael you linked to a codespace (which can't be accessed). Did you mean #253?

**Comment by deronnax** [comment]
for info, and unless I am wrong, #253 which you say you need, introduces another use of `xmlSecCryptoAppKeyLoad` (the one you commented) but you don't correct it in your PR. So if #253 get merged and then yours, the problem still happens

**Comment by ayakael** [comment]
@deronnax  This PR only adjusts the codebase as it is. I already alerted of this issue on #253 . Ideally, the author should update that, but if they don't and it is merged I can adjust this it in this PR.

**Comment by deronnax** [comment]
But in the first message of this PR, you say #253 is a requirement for this PR, so when this PR is merged, #253 will have been too, no?

**Comment by ayakael** [comment]
> But in the first message of this PR, you say #253 is a requirement for this PR, so when this PR is merged, #253 will have been too, no?

It doesn't actually require it. Sorry for the confusion. This PR can be merged as-is.

**Comment by ayakael** [comment]
I forget a few doc changes that I just fushed now

**Comment by deronnax** [comment]
@bgaifullin just merging this would fix the current compatibility issue with current libxml, thus fixing python-xmlsec for everyone, and turn the CI back to green. Would you please merge this?

**Comment by kloczek** [comment]
Is it possible to release new version because this PR? 🤔

**Pull request merged**
